### ISSUE TITLE
CQRS/Event sourcing

### ISSUE THREAD

**Issue by mquandalle** [thebarty/meteor-denormalized-views#1]
Hi @thebarty,

I find this package interesting, and as I see that you are actively working on it, I wonder if you are familiar with the Event sourcing architecture and with CQRS? The idea to have distinctions collections for writing and reading and a unidirectional data flow in between matches perfectly theses architecture principles, though the concepts naming is a little bit different—for example a “denormalized view” would be a “materialized view”.

So I just wanted to open a discussion on that, maybe these architectures could help to write the documentation or even to shape work in progress APIs.

**Comment by thebarty** [comment]
Hi @mquandalle, thanks for your kind words and funny that you bring those keywords into play. The idea for this package came in a discussion with my friend Daniel, who is into this kind of stuff. I am coming from old fashioned SQL and saw the commonality with SQL views. So yeah, for the sake of the future of this package it would be cool to extend its followership and make it accesible for those advanced concepts. I read up a bit - it might even be used for reporting-database creation (http://martinfowler.com/bliki/ReportingDatabase.html). I just updated the readme to introduce the compability to future readers. 👍

The API is quite beta - I'd love to keep it as simple and easy to get as possible.

Do you have any suggestions on how to improve this? Did you have a chance to try it out yet?
