### ISSUE TITLE
restrict on server only and use simple-schema from npm

### ISSUE THREAD

**Issue by macrozone** [thebarty/meteor-denormalized-views#3]
It seems that the package adds code to meteor client. It should be server-only.

also it should depend on simpleSchema if possible (maybe take newer version from npm instead of atmosphere-version)

**Comment by thebarty** [comment]
Yeah, in my current project I am actually using the "old" atmosphere versions of aldeed and I am a bit scared of upgrading (scared in the sense that I would have to invest too much time). 

Any ideas how to keep it backwards compatible when upgrading?
